name: Bug Report
description: 🐞 File a bug report
title: "[Bug]: "
labels: ["Kind/🍊 Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Explain the bug and give images if possible
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Walk us through all the steps on how to reproduce your issue
      value: |
        1.
        2.
        3.
        4.
    validations:
      required: true